FROM golang:1.23 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /api ./cmd/api

FROM gcr.io/distroless/base-debian12
COPY --from=builder /api /api
EXPOSE 8080
ENTRYPOINT ["/api"]